version: "3.8"
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=tima.py
      - FLASK_ENV=development
      - DATABASE=tima
      - DATABASE_USER=timadbuser
      - DATABASE_PASSWORD_FILE=/run/secrets/db_user_pwd
      - SECRET_KEY_FILE=/run/secrets/secret_key
    depends_on:
      - mariadb
    networks:
      - tima_network
    secrets:
      - db_user_pwd
      - secret_key

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=tima
      - MYSQL_USER=timadbuser
      - MYSQL_PASSWORD_FILE=/run/secrets/db_user_pwd
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - tima_network
    secrets:
      - db_user_pwd

volumes:
  db-volume:

networks:
  tima_network:

secrets:
  db_user_pwd:
    file: ./secrets/db_user_pwd.txt
  secret_key:
    file: ./secrets/secret_key.txt
